CREATE TABLE IF NOT EXISTS urls (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    original_url TEXT NOT NULL,
    short_url TEXT UNIQUE NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    expiration_date DATETIME NOT NULL DEFAULT (DATETIME(CURRENT_TIMESTAMP, '+6 month'))
);

CREATE INDEX IF NOT EXISTS idx_expiration_date ON urls (expiration_date);
